const albums = [
    {
        id:1,
        name: "Kraws Bohnz",
        album: "A Gift From me To Y'all",
        image: "./images/covers/A Gift From me To Y'all-1.jpg",
        composer: "Thabo Mashabela, Maphutha Aggrey",
        date: "February 14 2025",
        description: "Tracklist:",
        youtubeUrl: "https://www.youtube.com/watch?v=x8EZIMwoM5Q&list=OLAK5uy_kBeWP8etsnAtHaaX3cCFPxLGedxv0Sniw",
        geniuxUrl: "https://music.geniux.co.za/playing/album/88394678445/",
        albumTrackList: [
            { track: "1. Player's Take"},
            { track: "2. Panties Wet (Ft. Razor McPablo)"},
            { track: `3. Indwang'`},
            { track: "4. Wine O'Clock"},
            { track: "5. Sons to Mothers"},
            { track: `6. Killey Interlude`},
            { track: "7. Sky Rocket - Friends"},
            { track: " "},
            ]
    },

    {
        id:2,
        name: "Veteran Beatx",
        album: "For The Win EP",
        composer: "Maphutha Aggrey",
        image: "./images/covers/For The Win.jpeg",
        date: "July 24 2022",
        description: "Tracklist:",
        youtubeUrl: "",
        geniuxUrl: "https://music.geniux.co.za/playing/album/50504845357/",
        albumTrackList: [
            { track: "1. Love In The Streets (Ft. Da-Icke)"},
            { track: "2. Shots (Ft. La-Cool & Rod)"},
            { track: `3. Finesse (Ft. Kraws Bohnz & SASS)`},
            { track: "4. Street Lingo (Ft. Kraws Bohnz & Manila R)"},
            { track: "5. Racks (Ft. Marvel K & Da-Icke)"},
            { track: `6. No Limit (Ft. Keezy, Razor McPablo, Dray & Manila R)`},
            { track: "7. Special (Ft. Manila R)"},
            { track: " "},
            ]
    },

    {
        id:3,
        name: "Razor McPablo",
        album: "Kush Sesh Mixtape",
        composer: "Phemelo Manala, Maphutha Aggrey",
        image: "./images/covers/Kush Sesh.jpeg",
        date: "March 7 2021",
        description: "Tracklist:",
        youtubeUrl: "https://www.youtube.com/watch?v=GsWuwjP4eq0&list=OLAK5uy_lZg73EJHMYi8LRymqJKIauQWV9vIUAMeo",
        geniuxUrl: "https://music.geniux.co.za/spotify/playing/album/3PAe4S3aQSD8ZfSu5gklio/",
        albumTrackList: [
            { track: "1. Doubt You'll Listen"},
            { track: "2. Green Cereal, No Milk"},
            { track: `3. Trap Door`},
            { track: "4. Roll The Blunt"},
            { track: "5. Strawberry Babba"},
            { track: `6. Better Days`},
            { track: "7. Moving (Ft. Chutney)"},
            { track: "8. I Need"},
            { track: `9. K.I.N.G (Ft. Psycho)`},
            { track: "10. Stay True - Mixtape Version"},
            { track: "11. Fa Fa"},
            { track: "12. KWWK (Ft. LaCool)"},
            { track: `13. Rolling (ft. Manila R)`},
            { track: "14. Lover Boy Interlude"},
            { track: "15. Sugered"},
            { track: "16. Wake Up"},
            { track: `17. When I Wrote This`},
            { track: "18. Sik Outro"},
            { track: " "},
            ]
    
    },

    {
        id:4,
        name: "Rod",
        album: "Bad Kid Mixtape",
        composer: "Rodney Dolamo, Maphutha Aggrey",
        image: "./images/covers/Bad Kid.jpeg",
        date: "January 14 2022",
        description: "Tracklist:",
        youtubeUrl: "",
        geniuxUrl: "",
        albumTrackList: [
            { track: "1. Intro"},
            { track: "2. Bottom"},
            { track: `3. Niggas Are Actors`},
            { track: "4. Party"},
            { track: "5. Takin It Back (Ft. Savage x, MAnila R, Germtee)"},
            { track: `6. Bad Bitch`},
            { track: "7. Love, Money (Ft. Manila R)"},
            { track: "8. Sorry (Interlude)"},
            { track: "9. Dairy (Unmastered)"},
            { track: `10. Bad Kid`},
            { track: "11. Marijuana (Ft. Chutney & Manila R)"},
            { track: "12. Why Are We Broke"},
            { track: `13. Art In Me`},
            { track: "14. We'll Be Fine"},
            { track: " "},
            ]
    
    },

    {
        id:5,
        name: "Germtee",
        album: "Laco Cargo EP",
        composer: "German, Maphutha Aggrey",
        image: "./images/covers/Laco cargo.jpeg",
        date: "July 24 2022",
        description: "Tracklist:",
        youtubeUrl: "https://www.youtube.com/watch?v=OA4rdEUrrcM&list=OLAK5uy_m8zVPs4Oq_y6iDTcMqSHoy_VLrX1WNceI",
        geniuxUrl: "https://music.geniux.co.za/spotify/playing/album/0r0PMCC2diDn41ojS0f8oC/",
        albumTrackList: [
            { track: "1. Laco Cargo"},
            { track: "2. Something To Say"},
            { track: `3. On A Go`},
            { track: "4. Tla Le Sprite"},
            { track: "5. On The Drugs"},
            { track: " "},
            ]
    },
    

    {
        id:6,
        name: "Razor McPablo",
        album: "Paramount Mixtape",
        composer: "Phemelo Manala, Maphutha Aggrey",
        image: "./images/covers/Paramount Cover.jpg",
        date: "June 9 2024",
        description: "Tracklist:",
        youtubeUrl: "https://www.youtube.com/watch?v=f1GgR9R-4q0&list=OLAK5uy_lbo1sTNRN1vXynBEoin-WgBHK5T8hH288",
        geniuxUrl: "https://music.geniux.co.za/spotify/playing/album/4eVIevl9iPsQ9KDeqzCHol/",
        albumTrackList: [
            { track: "1. Corneng(Eish)"},
            { track: "2. Wishin"},
            { track: `3. Njwaka(Insprd.LEPANTA)`},
            { track: "4. Hello (Ft. Authentic & Judah Junior"},
            { track: "5. Trenches"},
            { track: `6. Pozi (Ft. Authentic)`},
            { track: "7. The Man"},
            { track: "8. From Time Freestyle"},
            { track: `9. Trust Interlude`},
            { track: "10. Let's Talk About It (Kraws Bohnz)"},
            { track: " "},
            ]
    
    },
    {
        id:7,
        name: "Manila R",
        album: "Mixtape Before OTT",
        composer: "Tshepiso Manala, Maphutha Aggrey",
        image: "./images/covers/Bfore OTT.jpeg",
        date: "October 9 2020",
        description: "Tracklist:",
        youtubeUrl: "",
        geniuxUrl: "",
        albumTrackList: [
            { track: "1. Intro Mixtape Before OTT"},
            { track: "2. Story To Tell (Ft. Da-Icke)"},
            { track: `3. Rehab`},
            { track: "4. Pray"},
            { track: "5. Someday (Ft. Da-Icke)"},
            { track: "6. Tlaala Remake"},
            { track: "7. Top Dawg"},
            { track: "8. Mara Thao"},
            { track: "9. Bounce"},
            { track: `10. Juice (Ft. Milk Dope)`},
            { track: "11. Focus (Ft. Germtee)"},
            { track: "12. Overall"},
            { track: `13. Sexy Song`},
            { track: "14. Rod's Outro"},
            { track: " "},
            ]
    
    },
]

const singles = [
    {
        id:1,
        name: "Sonwabile",
        single: "Ohhkay",
        composer: "Sonwabile Dyanose & Maphutha Aggrey",
        image: "./images/covers/iphi.jpeg",
        description: `Ohhkay is a song by a South African YouTuber and artist Sonwabile, featured on his EP, "IPHI", which officially debuted on Nov 29, 2024.`,
        date: "November 29 2024",
        genre: "Trap/Hip Hop",
        youtubeUrl: "https://www.youtube.com/watch?v=hdfQCyUVvMk",
        geniuxUrl: "https://music.geniux.co.za/spotify/playing/2gGnJC1CEiPBBlGDbBooOO",
    },

    {
        id:2,
        name: "Brocklyna",
        single: "Tseleng",
        composer: "Temosho & Maphutha Aggrey",
        image: "./images/covers/Tseleng.jpg",
        description: `An Afro Pop by Brocklyna from Limpopo. The song was featured on Limpopo Podcast.`,
        date: "July 31 2024",
        genre: "Afro Pop",
        youtubeUrl: "https://www.youtube.com/watch?v=XydYkZ6f0oc",
        geniuxUrl: "https://music.geniux.co.za/spotify/playing/album/15DOAdJWd1tsk8lLi6sg1W/",
    },

    {
        id:3,
        name: "Kraws Bohnz",
        composer: "Thabo Mashabela & Maphutha Aggrey",
        single: "Bra Kop",
        image: "./images/covers/Bra Kop Cover.jpeg",
        description: `Bra Kop' by Kraws Bohnz, a standout track from 1060.`,
        date: "May 12 2023",
        genre: "Trap/Hip Hop",
        youtubeUrl: "https://youtu.be/-ILDDEbr7o4?si=-ikXcBvoNPF1VSV7",
        geniuxUrl: "https://music.geniux.co.za/playing/26683031019",
    },

    {
        id:4,
        name: "Frank Gomez",
        single: "Motho Ke Sera",
        composer: "Nkateko Theodore Maranela & Maphutha Aggrey",
        image: "./images/covers/motho ke sera.jpeg",
        description: `MOTHO KE SERA. Produced by Veteran Beatx.`,
        date: "August 16 2024",
        genre: "Rap/Hip Hop",
        youtubeUrl: "https://youtu.be/C-GADo9AF5Q?si=dv2cRZdNDaVGcfNZ",
        geniuxUrl: "https://music.geniux.co.za/playing/40145037399",
    },
    {
        id:5,
        name: "Freeze Linet",
        composer: "Rodger Maphutha, Thapelo Maphutha & Maphutha Aggrey",
        single: "Lepara",
        image: "./images/covers/Lepara - Cover.jpeg",
        description: `A Hit by Freeze Linett, Produced by Thapelo, and engineered by Veteran Beatx`,
        date: "July 24 2020",
        genre: "Trap/Hip Hop",
        youtubeUrl: "https://www.youtube.com/watch?v=Bh7C9n4QEEU",
        geniuxUrl: "https://music.geniux.co.za/playing/7257058929",
    },

    {
        id:6,
        name: "Keah",
        single: "Kao Rata (Ft. Recky R)",
        composer: "Kea & Maphutha Aggrey",
        description: `An Amapiano/Deep House jam, Engineered by Veteran Beatx which features Keah & Recky R`,
        image: "./images/covers/Kao Rata.jpg",
        date: "November 5 2022",
        genre: "Amapiano",
        youtubeUrl: "https://youtu.be/xa0OiXmXC4M?si=9ZtNsBM-5RyC_kBP",
        geniuxUrl: "https://music.geniux.co.za/playing/88995415106",
    },
    {
        id:7,
        name: "Wasavii",
        composer: "Kgaogelo Rapolae & Maphutha Aggrey, Maphutha Evidence",
        single: "Shadow",
        description: `A classic rap by Wasavii, featured in his long-awaited, upcoming EP "W.A.N.T.S".`,
        image: "./images/covers/shadow.jpg",
        date: "July 24 2021",
        genre: "Rap/Hip Hop",
        youtubeUrl: "",
        geniuxUrl: "https://music.geniux.co.za/playing/4545615218",
    },
    {
        id:8,
        name: "Sbuu",
        single: "Jawbreaker",
        composer: "Sibusiso Sijeku & Maphutha Aggrey",
        description: `Banger from Sonwabile's videographer 'Sbuu', featured on his project 'All In One EP' Produced By Veteran Beatx & Lucent.exe`,
        image: "./images/covers/jawbreaker.jpeg",
        date: "September 19 2024",
        genre: "Trap/Hip Hop",
        youtubeUrl: "https://youtu.be/BRDTDkoo2cw?si=6vMhj8B6dgXhubTA",
        geniuxUrl: "https://music.geniux.co.za/playing/35288251013",
    },

    {
        id:9,
        name: "Savage X",
        single: "Nobody Safe",
        composer: "Seun & Maphutha Aggrey",
        description: `Nobody Safe, a single track by Savage X (SVG X), Engineered By Veteran Beatx`,
        image: "./images/covers/not-safe.jpg",
        date: "April 19 2021",
        genre: "Trap/Hip Hop",
        youtubeUrl: "",
        geniuxUrl: "https://music.geniux.co.za/playing/1534510691",
    },

    {
        id:10,
        name: "Corey",
        single: "Money",
        composer: "Ronald Tladi & Maphutha Aggrey",
        description: `Money, a single track by Corey, Produced By Veteran Beatx`,
        image: "./images/covers/Money - Cover.jpg",
        date: "November 11 2023",
        genre: "Trap/Hip Hop",
        youtubeUrl: "",
        geniuxUrl: "https://music.geniux.co.za/playing/65053451666",
    },
    {
        id:11,
        name: "Germtee",
        single: "Cha-Cha (Ft. SASS)",
        composer: "German, Tsebo & Maphutha Aggrey",
        description: `Cha Cha, featuring SASS, Re-Produced By Veteran Beatx, Released on: 2021-10-13`,
        image: "./images/covers/Cha Cha.jpg",
        date: "October 10 2021",
        genre: "Trap/Hip Hop",
        youtubeUrl: "https://youtu.be/-5IpaO10nzU?si=N8-x6YOWH-kL8JfM",
        geniuxUrl: "https://music.geniux.co.za/spotify/playing/album/32V5kMPpQQgjaDGwmMutxj/",
    },
    {
        id:12,
        name: "Freeze Linett",
        single: "Sparne",
        composer: "Rodger Maphutha & Maphutha Aggrey",
        description: `Hard Trap song by Freeze Linett, Produced By Veteran Beatx`,
        image: "./images/covers/Sparne.jpg",
        date: "October 10 2023",
        genre: "Trap/Hip Hop",
        youtubeUrl: "",
        geniuxUrl: "https://music.geniux.co.za/playing/75676034544",
    },
    {
        id:13,
        name: "Milk Dope",
        single: "Unstoppable",
        composer: "Bruce Bapela & Maphutha Aggrey",
        description: `Unstoppable, featuring Issa Jay, Re-Produced By Veteran Beatx`,
        image: "./images/covers/Unstoppable.png",
        date: "August 6 2021",
        genre: "Trap/Hip Hop",
        youtubeUrl: "",
        geniuxUrl: "https://music.geniux.co.za/playing/7034753845/",
    },
    {
        id:14,
        name: "Kraws Bohnz",
        single: "Sobbing",
        composer: "Thabo Mashabela & Maphutha Aggrey",
        description: `Kinda touching sad song by Kraws Bohnz, Produced By Veteran Beatx`,
        image: "./images/covers/Sobbing Cover.jpeg",
        date: "May 12 2023",
        genre: "Rap/Hip Hop",
        youtubeUrl: "https://youtu.be/HO8XVfF0n6o?si=D5AwQ0UroYNgdhq0",
        geniuxUrl: "https://music.geniux.co.za/playing/38795547441/",
    },
    {
        id:15,
        name: "Manila R",
        single: "Top 7",
        composer: "Tshepiso Manala & Maphutha Aggrey",
        description: `Veteran Beatx's first banger he produced, Dropped in 2017 by Manila R`,
        image: "./images/covers/Top  Seven - Cover.jpeg",
        date: "December 10 2017",
        genre: "Trap/Hip Hop",
        youtubeUrl: "",
        geniuxUrl: "",
    },
    {
        id:16,
        name: "Rod",
        single: "Marijuana 2.0",
        composer: "Rodney Dolamo, Tshepiso Manala & Maphutha Aggrey",
        description: `Marijuana 2.0 featuring Chutney, Manila R, Kraws Bohnz, Razor McPablo, Savage X and Germtee`,
        image: "./images/covers/Marijuana.jpeg",
        date: "April 20 2024",
        genre: "Trap/Hip Hop",
        youtubeUrl: "",
        geniuxUrl: "",
    },
    {
        id:17,
        name: "Corey",
        single: "Success",
        composer: "Ronald Tladi & Maphutha Aggrey",
        description: `Success, a single track by Corey, Produced By Veteran Beatx`,
        image: "./images/covers/Success - Cover.jpg",
        date: "September 2 2023",
        genre: "Trap/Hip Hop",
        youtubeUrl: "",
        geniuxUrl: "https://music.geniux.co.za/playing/29948781798",
    },
    {
        id:18,
        name: "Kraws Bohnz",
        single: "Praise The Lord",
        composer: "Thabo Mashabela, Manala Phemelo, Evidence Maphutha & Maphutha Aggrey",
        image: "./images/covers/Praise The Lord - Cover.jpeg",
        description: `Praise The Lord' by Kraws Bohnz & Razor McPablo, Produced by Notorioux and engineered by Veteran Beatx.`,
        date: "August 4 2020",
        genre: "Rap/Hip Hop",
        youtubeUrl: "",
        geniuxUrl: "https://music.geniux.co.za/playing/40145037399",
    },
    {
        id:19,
        name: "Kraws Bohnz",
        single: "Respect",
        composer: "Thabo Mashabela & Maphutha Aggrey",
        image: "./images/covers/respect.jpeg",
        description: `Respect' by Kraws Bohnz, Dropped in 2020, Produced by Veteran Beatx.`,
        date: "May 22 2020",
        genre: "Rap/Hip Hop",
        youtubeUrl: "",
        geniuxUrl: "https://music.geniux.co.za/playing/19104390562",
    },
]

    const beats = [
        {
            id:1,
            name: "Veteran Beatx",
            description: "Blxckie, The Qwellers, Baby Daiz, Sonwabile & Usimamane - Type Beat",
            composer: "Maphutha Aggrey",
            beat: "G Wagon",
            image: "./images/beats/G Wagon.jpg",
            date: "February 14 2025",
            youtubeUrl: "https://youtu.be/HJawQyeuEds?si=HfztXJv81ycByuNH",

            beatTrackList: [
                { track: "You must credit (prod. veteran beatx) in the title"},
                { track: "For inquiries:"},
                { track: `📧 veteranbeatx@gmail.com `},
                { track: "☎️ 076 521 6787 "},
               ]
        },
        {
            id:2,
            name: "Veteran Beatx",
            description: "Usimamane, Blxckie, Qwellers & A-Reece - Type Beat",
            composer: "Maphutha Aggrey",
            beat: "2025",
            image: "./images/beats/2025.jpg",
            date: "July 24 2022",
            youtubeUrl: "https://youtu.be/zOaetDeGSuU?si=D-tVrabjRzdEpRaW",
            beatTrackList: [
                { track: "You must credit (prod. veteran beatx) in the title"},
                { track: "For inquiries:"},
                { track: `📧 veteranbeatx@gmail.com `},
                { track: "☎️ 076 521 6787 "},
            ]       
        },
        {
            id:3,
            name: "Veteran Beatx",
            description: "KindlyNxsh Type Beat",
            composer: "Maphutha Aggrey",
            beat: "Soldier",
            image: "./images/beats/Soldier.jpg",
            date: "March 7 2021",
            youtubeUrl: "https://youtu.be/KKcAyYo1h18?si=pZAc4XVG3SzsF6UK",
            beatTrackList: [
                { track: "You must credit (prod. veteran beatx) in the title"},
                { track: "For inquiries:"},
                { track: `📧 veteranbeatx@gmail.com `},
                { track: "☎️ 076 521 6787 "},
              ]
        },
        {
            id:4,
            name: "Veteran Beatx",
            description: "Baby Daiz, KindlyNxsh & Blxckie - Type Beat",
            composer: "Maphutha Aggrey",
            beat: "2 for 10",
            image: "./images/beats/B Daiz.jpg",
            date: "January 14 2022",
            youtubeUrl: "https://youtu.be/hAUz63uWqfY?si=5fv0aogJtzGIRXfZ",
            beatTrackList: [
                { track: "You must credit (prod. veteran beatx) in the title"},
                { track: "For inquiries:"},
                { track: `📧 veteranbeatx@gmail.com `},
                { track: "☎️ 076 521 6787 "},
          ]
        },
        {
            id:5,
            name: "Veteran Beatx",
            description: "Brotherkupa, jaykatana, Blxckie, LaCabra & Lowfeye - Type Beat",
            composer: "Maphutha Aggrey",
            beat: "Limpopo",
            image: "./images/beats/Brotherkupa.jpg",
            date: "July 24 2022",
            youtubeUrl: "https://www.youtube.com/watch?v=Hj4hCftb3nY",
            beatTrackList: [
                { track: "You must credit (prod. veteran beatx) in the title"},
                { track: "For inquiries:"},
                { track: `📧 veteranbeatx@gmail.com `},
                { track: "☎️ 076 521 6787 "},
           ]
        },
        {
            id:6,
            name: "Veteran Beatx",
            description: "Blxckie, The Qwellers, Usimamane & KindlyNxsh - Type Beat",
            composer: "Maphutha Aggrey",
            beat: "Steppin",
            image: "./images/beats/Steppin.jpg",
            date: "June 9 2024",
            youtubeUrl: "https://youtu.be/qXCE8uWC-vA?si=QZWcmwk6nS1bR51N",
            beatTrackList: [
                { track: "You must credit (prod. veteran beatx) in the title"},
                { track: "For inquiries:"},
                { track: `📧 veteranbeatx@gmail.com `},
                { track: "☎️ 076 521 6787 "},
       
                ]
        },
        {
            id:7,
            name: "Veteran Beatx",
            description: "Blxckie, Leodaleo, Qwellers, Usimamane & Brotherkupa Type Beat ",
            composer: "Maphutha Aggrey",
            beat: "Scorpion",
            image: "./images/beats/scorpion.jpg",
            date: "February 14 2025",
            youtubeUrl: "https://youtu.be/1gF6ZOAxNGI?si=zwOTIyyOzd8hz-kO",

            beatTrackList: [
                { track: "You must credit (prod. veteran beatx) in the title"},
                { track: "For inquiries:"},
                { track: `📧 veteranbeatx@gmail.com `},
                { track: "☎️ 076 521 6787 "},
               ]
        },
        {
            id:8,
            name: "Veteran Beatx",
            description: "Usimamane, Sjava, Emtee - Type Beat",
            composer: "Maphutha Aggrey",
            beat: "Fear",
            image: "./images/beats/Fear.jpg",
            date: "July 24 2022",
            youtubeUrl: "https://youtu.be/HMomCzPScOw?si=7_Ay8oyj3n3tRYFo",
            beatTrackList: [
                { track: "You must credit (prod. veteran beatx) in the title"},
                { track: "For inquiries:"},
                { track: `📧 veteranbeatx@gmail.com `},
                { track: "☎️ 076 521 6787 "},
            ]       
        },
        {
            id:9,
            name: "Veteran Beatx",
            description: "BrotherKupa, Kindlynxsh, Blxckie, BabyDaiz & Usimamane - Type Beat",
            composer: "Maphutha Aggrey",
            beat: "Rick May",
            image: "./images/beats/Rick May.jpg",
            date: "March 7 2021",
            youtubeUrl: "https://youtu.be/NxSUgDnfKTw?si=M1_k-HaMcxvONKqW",
            beatTrackList: [
                { track: "You must credit (prod. veteran beatx) in the title"},
                { track: "For inquiries:"},
                { track: `📧 veteranbeatx@gmail.com `},
                { track: "☎️ 076 521 6787 "},
              ]
        },
        {
            id:10,
            name: "Veteran Beatx",
            description: "Mashbeatz, Wordz, Usimamane, Dj Sliqe, Mochen & Nasty C - Type Beat",
            composer: "Maphutha Aggrey",
            beat: "Revenge",
            image: "./images/beats/revenge.jpg",
            date: "January 14 2022",
            youtubeUrl: "https://youtu.be/cdaaOgJNLVw?si=cSmH8ay7On4WeZy7",
            beatTrackList: [
                { track: "You must credit (prod. veteran beatx) in the title"},
                { track: "For inquiries:"},
                { track: `📧 veteranbeatx@gmail.com `},
                { track: "☎️ 076 521 6787 "},
          ]
        },
        {
            id:11,
            name: "Veteran Beatx",
            description: "Blxckie, Qwellers, Nasty C, Usimamane, kindlynxsh & Brother Kupa - Type Beat",
            composer: "Maphutha Aggrey",
            beat: "Crazy",
            image: "./images/beats/Crazy.jpeg",
            date: "July 24 2022",
            youtubeUrl: "https://youtu.be/BVoG-Ya55k4?si=LDiW6E8FXt1Q_cre",
            beatTrackList: [
                { track: "You must credit (prod. veteran beatx) in the title"},
                { track: "For inquiries:"},
                { track: `📧 veteranbeatx@gmail.com `},
                { track: "☎️ 076 521 6787 "},
           ]
        },
        {
            id:12,
            name: "Veteran Beatx",
            description: "Blxckie, The Qwellers, Usimamane & KindlyNxsh - Type Beat",
            composer: "Maphutha Aggrey",
            beat: "Attack",
            image: "./images/beats/Attack.jpeg",
            date: "June 9 2024",
            youtubeUrl: "https://youtu.be/qXCE8uWC-vA?si=QZWcmwk6nS1bR51N",
            beatTrackList: [
                { track: "You must credit (prod. veteran beatx) in the title"},
                { track: "For inquiries:"},
                { track: `📧 veteranbeatx@gmail.com `},
                { track: "☎️ 076 521 6787 "},
       
                ]
        },
        {
            id:13,
            name: "Veteran Beatx",
            description: "Blxckie, Flow Jones Jr, Usimamane & BrotherKupa - Type Beat",
            composer: "Maphutha Aggrey",
            beat: "Martin",
            image: "./images/beats/martin.jpg",
            date: "July 24 2022",
            youtubeUrl: "https://youtu.be/ug2iNNrx9i8?si=UXwN01KHnw-8921G",
            beatTrackList: [
                { track: "You must credit (prod. veteran beatx) in the title"},
                { track: "For inquiries:"},
                { track: `📧 veteranbeatx@gmail.com `},
                { track: "☎️ 076 521 6787 "},
            ]       
        },
        {
            id:14,
            name: "Veteran Beatx",
            description: "Blxckie, Brotherkupa, Usimamane, Qwellers - Sastii & Sonwabile - Type Beat",
            composer: "Maphutha Aggrey",
            beat: "Clock",
            image: "./images/beats/clock.jpg",
            date: "March 7 2021",
            youtubeUrl: "https://youtu.be/2omfXUc0Ofs?si=BCPvzTZ9kr2G-54P",
            beatTrackList: [
                { track: "You must credit (prod. veteran beatx) in the title"},
                { track: "For inquiries:"},
                { track: `📧 veteranbeatx@gmail.com `},
                { track: "☎️ 076 521 6787 "},
              ]
        },
        {
            id:15,
            name: "Veteran Beatx",
            description: "Blxckie, Usimamane, LaCabra, Lowfeye & Brotherkupa - Type Beat",
            composer: "Maphutha Aggrey",
            beat: "Dangerous",
            image: "./images/beats/Dangerous.jpeg",
            date: "January 14 2022",
            youtubeUrl: "https://youtu.be/FDXVL8gJkAs?si=LKxD-S7FtmifC4Pk",
            beatTrackList: [
                { track: "You must credit (prod. veteran beatx) in the title"},
                { track: "For inquiries:"},
                { track: `📧 veteranbeatx@gmail.com `},
                { track: "☎️ 076 521 6787 "},
          ]
        },
        {
            id:16,
            name: "Veteran Beatx",
            description: "Usimamane, 25k, Blxckie, Tony Dayimane & Mashbeatz - Type Beat",
            composer: "Maphutha Aggrey",
            beat: "Culture",
            image: "./images/beats/Culture.jpeg",
            date: "July 24 2022",
            youtubeUrl: "https://youtu.be/9gvotYtcRaI?si=6MJ4hQPUBP0Ultaj",
            beatTrackList: [
                { track: "You must credit (prod. veteran beatx) in the title"},
                { track: "For inquiries:"},
                { track: `📧 veteranbeatx@gmail.com `},
                { track: "☎️ 076 521 6787 "},
           ]
        },


    ]
    
        const mixtapes = [
            {
                id:1,
                name: "Veteran beatx",
                composer: "Maphutha Aggrey",
                mixtape: "2025 Mixtape - Hip Hop",
                description: `Hip Hop Mixtape, featuring the hottest tracks of 2024, bangers from: Usimamane, Kindlynxsh, Loatinover Pounds, Mashbeatz and more! With 80% of the tracks reppin' South African hip hop. Experience the future of SA hip hop!`,
                image: "./images/covers/2025 Mixtape.jpg",
                date: "January 20 2025",
                geniuxUrl: "https://music.geniux.co.za/playing/60465194077",
            },
            {
                id:2,
                name: "Veteran Beatx",
                mixtape: "Valentine Mixtape",
                composer: "Maphutha Aggrey",
                description: `RnB Valentine Mixtape, featuring the hottest RnB and AfroBeat tracks, bangers from: Blxckie, Drake, Aka and more! Experience the future of RnB!`,
                geniuxUrl: "https://music.geniux.co.za/playing/29789702829",
                image: "./images/covers/Valentine Mix.jpg",
                date: "February 14 2024",
            },
            {
                id:3,
                name: "Veteran Beatx",
                mixtape: "Hip Hop Mixtape",
                composer: "Maphutha Aggrey",
                description: `Tribute Mixtape to AKA and Costa Titch, featuring the hottest SA tracks, bangers from: Blxckie, Thato Saul, Aka and more! Experience the future of SA hip hop!`,
                geniuxUrl: "https://music.geniux.co.za/playing/80937729126",
                image: "./images/covers/Mix tribute cover.jpg",
                date: "March 7 2023",
            },
            {
                id:4,
                name: "Veteran Beatx",
                mixtape: "Ndwalp 007",
                composer: "Maphutha Aggrey",
                description: `Veteran Beatx featured on a Ndwalp mixtapes, With the bangers from: Gunna, Drake, Young Thug and more! Experience the future of Trap hip hop!`,
                geniuxUrl: "https://music.geniux.co.za/playing/39712780360",
                image: "./images/covers/Ndwalp Mix Cover.jpg",
                date: "January 14 2022",
            },
            {
                id:5,
                name: "Veteran Beatx",
                mixtape: "Hip Hop Mix 2021",
                composer: "Maphutha Aggrey",
                description: `Trap Mixtape, featuring the hottest trap tracks, bangers from: Gunna, Roddy Richh, Nasty C and more! Experience the future of Trap hip hop!`,
                image: "./images/covers/Hip Hop Mix.png",
                date: "February 28 2021",
                geniuxUrl: "https://music.geniux.co.za/playing/6360569476",
            },
            {
                id:6,
                name: "Veteran Beatx",
                mixtape: "Food Garden Mix 2021",
                composer: "Maphutha Aggrey",
                description: `Tribute Mixtape to the one of the best events in 1060 and a big one to Riky Rick, featuring the hottest trap tracks, bangers from: A-Reece, Blxckie, Riky Rick and more! Experience the future of Trap hip hop!`,
                image: "./images/covers/Food Garden Cover.jpg",
                date: "March 28 2022",
                geniuxUrl: "https://music.geniux.co.za/playing/5959260720",
            },
            {
                id:7,
                name: "Veteran Beatx",
                mixtape: "Mixtape 03 2022",
                composer: "Maphutha Aggrey",
                description: `A short mix featuring the South African trap. Put Together By Veteran Beatx, bangers from: Lucasraps, Blxckie, Nasty C and more! Experience the future of SA Trap hip hop!`,
                image: "./images/covers/mix03.jpeg",
                date: "December 27 2022",
                geniuxUrl: "https://music.geniux.co.za/playing/20543636841",
            },

        ]
      
